apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-app-builder
  labels:
    app: ai-app-builder
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-app-builder
  template:
    metadata:
      labels:
        app: ai-app-builder
    spec:
      containers:
        - name: ai-app-builder
          image: aiappbuilderacrruchi2026.azurecr.io/ai-app-builder:latest
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          env:
            - name: GROQ_API_KEY
              valueFrom:
                secretKeyRef:
                  name: groq-api-key
                  key: GROQ_API_KEY
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"