apiVersion: v1
kind: Service
metadata:
  name: ai-app-builder-service
  labels:
    app: ai-app-builder
spec:
  type: LoadBalancer
  selector:
    app: ai-app-builder
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000